import React from "react";

export const texts = {
  onboardingTitle:["Ganha dinheiro  seguindo estratégias de Bettimers", "Make money following Bettimers strategies"],
  onboardingParag:["Com o Bettimers você aumenta a sua renda extra nas casas de apostas nos aviatores.","With Bettimers you can increase your extra income at aviator betting houses."],
  onboardingBtn:["Começar agora", "Start now"],
  nextBtn:["Próximo bet", "Next bet"],
  seeAll:["Ver todas", "See all"],
  allNextBets:["Todos próximos bets", "All next bets"],
  signUp:["Inscrever-se","Sign-up"],
  fullName:["Nome completo", "Full name"],
  login:["Conecte-se","Login"],
  passwordLabel:["Senha", "Password"],
  repeatPasswordLabel:["Repete a senha", "Repeat password"],
  passwordDontMatch:["As senhas não combina!", "Password don't match!"],
  forgotPassword:["Esqueceu sua senha?", "Forgot password?"],
  rememberPassword:["Eu lembro da minha senha","I remember my password"],
  dontHaveAccount:["Não tenho conta", "I don't have account"],
  iHaveAccount:["Já tenho conta", "I am a member"],
  invalidFullName:["Nome completo inválido", "Invalid full name"],
  invalidEmail:["Endereço de e-mail inválido!","Invalid email!"],
  invalidPassword:["Senha inválido","Invalid password!"],
  emailAlreadyInUse:["O endereço de e-mail já está em uso por outra conta!" ,"The email address is already in use by another account"],
  wrongPassword:["Senha incorreta","Wrong password!"],
  userNotFound:["Usuário não cadastrado!","User not registered!"],
  weakPassword:["A senha deve ter pelo menos 6 caracteres", "Password should be at least 6 characters!"],
  requestResetPassword:["Redefinição de senha", "Reset password"],
  request:["Solicitar", "Request"],
  requestSent:["Solicitação enviada, verifique a sua caixa de emails", "Request sent, check your email inbox"],
  resetPasswordTitle:["Redefinir senha","Reset password"],
  save:["Salvar", "Save"],
  copySuccessful:["Copiado com sucesso!", "Successful copied!"],
  noSubscription:["Você não está subscrito", "You are not subscribed"],
  subscribed:["Subscrito", "Subscribed"],
  subscribe:["toque para subscrever-te","click here to subscribe!"],
  logout:["Sair","Logout"],
  changePassword:["Trocar senha","Change password"],
  imageNotsupported:["O arquivo selecionado não é suportada!","The selected file is not supported!"],
  editImage:["Editar imagem","Edit image"],
  editName:["Editar o nome","Edit Name"],
  packagesTitle:["Eleva melhores resultados de apostas no aviator com acesso premium.","Improve better betting results on the aviator with premium access."],
  access:["Acesso", "Access"],
  monthly:["mensal", "monthly"],
  quarterly:["trimestrial","quarterly"],
  yearly:["Anual","yearly"],
  continues:["Continuar", "Continue"],
  economize:["Economize","Save"],
  messagePackage:["Eu quero pagar o", "I want to pay for"],
  expireAt:["Expira em", "Expire at"],
  isBanned:["Sua conta foi banido deste app","Your account was banned from this app"]
}